Fix build for latest core 4.0.0 snapshot
micronaut-projects/micronaut-multitenancy pull request #144
Opened 2022-11-04 15:00 UTC by timyates

2022-11-07 08:54 UTC, sdelamo requested changes

2022-11-07 08:54 UTC, sdelamo commented on multitenancy/build.gradle
> +    testImplementation(mn.micronaut.jackson.databind)
can we use `serde` instead?

2022-11-07 09:59 UTC, timyates commented on multitenancy/build.gradle
> +    testImplementation(mn.micronaut.jackson.databind)
Done in https://github.com/micronaut-projects/micronaut-multitenancy/pull/144/commits/a8a4ddfad57daf21ca172723c45955762ec00331

Had to make a class `@Serdeable` too

2022-11-15 16:33 UTC, sdelamo approved these changes

2022-11-15 16:34 UTC, merged