Refactor `SubdomainTenantResolver`; use `HttpHostResolver` if available
micronaut-projects/micronaut-multitenancy pull request #225
Opened 2023-09-01 12:36 UTC by guillermocalvo

2023-09-08 06:47 UTC, sdelamo requested changes
Should we not consider the apex domain a domain without a subdomain? 

I think for `test.com` the subdomain resolver should return default. 

Please, add a test with for a url such as `http://super.duper.domain.co.uk`. Where the subdomain I assume it should be `super.duper`

It seems publicsuffix.org  is the best source for the list of public suffixes https://publicsuffix.org/list/effective_tld_names.dat

2023-09-08 06:47 UTC, sdelamo commented on multitenancy/build.gradle.kts
> +    api(mn.micronaut.http.server)
make this compileOnly

2023-09-08 06:47 UTC, sdelamo commented on multitenancy/src/main/java/io/micronaut/multitenancy/tenantresolver/SubdomainTenantResolver.java
>  @Requires(property = SubdomainTenantResolverConfigurationProperties.PREFIX + ".enabled", value = StringUtils.TRUE, defaultValue = StringUtils.FALSE)
annotate with `@Requires(classes = HttpHostResolver.class)`?

2023-09-08 06:47 UTC, sdelamo commented on multitenancy/src/main/java/io/micronaut/multitenancy/tenantresolver/SubdomainTenantResolver.java
> +        this.httpHostResolver = null;
this would be better as         `this.httpHostResolver = new DefaultHttpHostResolver(new HttpServerConfiguration(), null);`

2023-09-08 06:47 UTC, sdelamo commented on multitenancy/src/main/java/io/micronaut/multitenancy/tenantresolver/SubdomainTenantResolver.java
> +        return Optional.ofNullable(httpHostResolver)
if we initialise the `httpHostResolver` see comment above can we remove the wrapping in an optional.

2023-09-08 09:19 UTC, guillermocalvo commented on multitenancy/src/main/java/io/micronaut/multitenancy/tenantresolver/SubdomainTenantResolver.java
>  @Requires(property = SubdomainTenantResolverConfigurationProperties.PREFIX + ".enabled", value = StringUtils.TRUE, defaultValue = StringUtils.FALSE)
@sdelamo Shouldn't we use `@Requires(bean = HttpHostResolver.class)`?

After all, the injectable constructor expects an actual `HttpHostResolver` bean. 🤔

2023-09-11 10:00 UTC, sdelamo commented on multitenancy/src/main/java/io/micronaut/multitenancy/tenantresolver/SubdomainTenantResolver.java
>  @Requires(property = SubdomainTenantResolverConfigurationProperties.PREFIX + ".enabled", value = StringUtils.TRUE, defaultValue = StringUtils.FALSE)
yes, `@Requires(bean = HttpHostResolver.class)` it is ok as well.

2023-09-11 10:06 UTC, sdelamo requested changes
I think adding _guava_ as a dependency (which should be only as much a `compileOnly` dependency)  is an overkill. I don't want Micronaut Multi-Tenancy to depend on _guava_. What can we do instead?

2023-09-11 16:33 UTC, sdelamo commented
> > I think adding _guava_ as a dependency (which should be only as much a `compileOnly` dependency) is an overkill. I don't want Micronaut Multi-Tenancy to depend on _guava_. What can we do instead?
> 
> So the Public Suffix website lists [two other possible Java libraries](https://publicsuffix.org/learn/):
> 
> * https://github.com/hamano/regdom4j/
> * https://github.com/whois-server-list/public-suffix-list
> 
> But I'm not sure if those are going to be as well-maintained or even as handy as Guava.
> 
> As you can see, the list of public suffixes is huge (9k+ entries). I don't believe that developing and maintaining the source code to parse all possible internet domain names should be in scope in the context of **micronaut-multitenancy**.
> 
> @sdelamo A much simpler alternative would be to let users define their own suffixes via configuration property. `SubdomainTenantResolver` would then remove those prefixes from the hostname to resolve a tenant identifier. Without this config, it would simply remove the TLD (which is the current behavior).

I created a [PR](https://github.com/micronaut-projects/micronaut-multitenancy/pull/234) based on this one which  adds multiple implementations and keeps a naive `SubdomainTenantResolver`. Let me know what you think.

2023-09-12 09:30 UTC, closed without merging