Multiple implementations of Subdomain tenant resolver supporting every domain suffix
micronaut-projects/micronaut-multitenancy pull request #234
Opened 2023-09-11 16:24 UTC by sdelamo

2023-09-11 17:11 UTC, guillermocalvo requested changes
I don't think `SubdomainTenantResolver` will resolve hostnames properly as it is now 🤔

2023-09-11 17:11 UTC, guillermocalvo commented on multitenancy/src/main/java/io/micronaut/multitenancy/tenantresolver/PublicSuffixListSubdomainTenantResolver.java
> +            int index = host.indexOf("." + domain);
```suggestion
            int index = host.lastIndexOf("." + domain);
```

2023-09-11 17:11 UTC, guillermocalvo commented on multitenancy/src/main/java/io/micronaut/multitenancy/tenantresolver/SubdomainTenantResolver.java
> +            return host.substring(0, host.indexOf("."));
This will return only the last subdomain:

- ✅ `test.com` resolves to: `DEFAULT`
- ✅ `duper.test.com` resolves to: `duper`
- ❗ `super.duper.test.com` resolves to: `super`
  - Should be: `super.duper`

2023-09-11 21:04 UTC, sdelamo commented on multitenancy/src/main/java/io/micronaut/multitenancy/tenantresolver/SubdomainTenantResolver.java
> +            return host.substring(0, host.indexOf("."));
I added a test https://github.com/micronaut-projects/micronaut-multitenancy/pull/234/commits/2d717f89ac2db5295a2f5b08b4e9b6172ac145e1

2023-09-11 21:06 UTC, sdelamo commented
> I don't think `SubdomainTenantResolver` will resolve hostnames properly as it is now 🤔

Not sure what you mean, we have some tests: https://github.com/micronaut-projects/micronaut-multitenancy/blob/guava-compile-only/multitenancy/src/test/groovy/io/micronaut/multitenancy/tenantresolver/SubdomainTenantResolverEnabledSpec.groovy#L83-L92

2023-09-12 08:57 UTC, guillermocalvo commented
> > I don't think `SubdomainTenantResolver` will resolve hostnames properly as it is now 🤔
> 
> Not sure what you mean, we have some tests: 

@sdelamo You [fixed the implementation here](https://github.com/micronaut-projects/micronaut-multitenancy/commit/2d717f89ac2db5295a2f5b08b4e9b6172ac145e1#diff-f9eb69c48c4048cdd433baaa8c3ff84eb9921737ea05c5e1f4c114cb0a795478R66). Previously, it was simply returning `host.substring(0, host.indexOf("."));`. That's what I meant.

2023-09-12 08:59 UTC, guillermocalvo approved these changes

2023-09-12 09:30 UTC, merged