Tenant Argument Binder
micronaut-projects/micronaut-multitenancy pull request #343
Opened 2024-10-30 13:04 UTC by sdelamo

This adds an api `Tenant`, which represents the abstract notion of a tenant.

Moreover, it adds a RequestFilter to resolve the tenant and set it as a request attribute.

This pull request adds an argument binder that uses the request attribute resolved in the filter. Because of this, a user can bind the tenant as a controller method parameter

2024-10-30 13:05 UTC, sdelamo commented on multitenancy/src/main/java/io/micronaut/multitenancy/filter/TenantResolverFilter.java
> +        Optional<Serializable> tenantOptional = resolveTenant(request);
I attempt first to resolve with a `HttpRequestTenantResolver` to avoid using `ServerRequestContext` if possible.

2024-10-30 13:16 UTC, graemerocher requested changes

2024-10-30 13:16 UTC, graemerocher commented on multitenancy/src/main/java/io/micronaut/multitenancy/filter/TenantResolverFilter.java
> +final class TenantResolverFilter implements Ordered {
this should only be enabled if you have an active `HttpRequestTenantResolver`

2024-10-30 13:16 UTC, graemerocher commented on multitenancy/src/main/java/io/micronaut/multitenancy/filter/TenantTypedRequestArgumentBinder.java
> +        Optional<BindingResult<Tenant>> bindingResult = source.getAttribute(TenantResolverFilter.ATTRIBUTE_TENANT, String.class)
what if the resolved tenant is not a string? What if it already implements `Tenant`?

2024-10-30 13:16 UTC, graemerocher commented on multitenancy/src/main/java/io/micronaut/multitenancy/Tenant.java
> +@FunctionalInterface
I wouldn't add this annotation. It assumes we will never have other methods in this interface

2024-10-30 13:16 UTC, graemerocher commented on multitenancy/src/main/java/io/micronaut/multitenancy/filter/package-info.java
> +@Requires(property = TenantResolverFilterConfigurationProperties.PREFIX + ".enabled",
extract a constant for enabled

2024-10-30 13:16 UTC, graemerocher commented on multitenancy/src/main/java/io/micronaut/multitenancy/Tenant.java
> +    String id();
how do we know the id will always be a string? Might make sense to use a generic here

2024-10-30 15:18 UTC, sdelamo commented on multitenancy/src/main/java/io/micronaut/multitenancy/filter/package-info.java
> +@Requires(property = TenantResolverFilterConfigurationProperties.PREFIX + ".enabled",
resolved via https://github.com/micronaut-projects/micronaut-multitenancy/pull/343/commits/68ea53b2fd32d079861454abcea1bb626c1e916c

2024-10-30 15:19 UTC, sdelamo commented on multitenancy/src/main/java/io/micronaut/multitenancy/Tenant.java
> +@FunctionalInterface
resolved via https://github.com/micronaut-projects/micronaut-multitenancy/pull/343/commits/9c78e236e8e5b6c890c4ad5ea42d23e855e160c0

2024-10-30 15:19 UTC, sdelamo commented on multitenancy/src/main/java/io/micronaut/multitenancy/Tenant.java
> +    String id();
something like https://github.com/micronaut-projects/micronaut-multitenancy/pull/343/commits/6072e5f75b9daff4a540273e415ac8a08dc5db64 ?

2024-10-30 15:24 UTC, sdelamo commented on multitenancy/src/main/java/io/micronaut/multitenancy/filter/TenantResolverFilter.java
> +final class TenantResolverFilter implements Ordered {
resolved via https://github.com/micronaut-projects/micronaut-multitenancy/pull/343/commits/a3ae9125a5b6d91764b60a0e9920ce6b99bccfd3

2024-10-30 15:25 UTC, sdelamo commented on multitenancy/src/main/java/io/micronaut/multitenancy/filter/TenantTypedRequestArgumentBinder.java
> +        Optional<BindingResult<Tenant>> bindingResult = source.getAttribute(TenantResolverFilter.ATTRIBUTE_TENANT, String.class)
I changed this to `SerializableTenant`

2024-10-31 08:51 UTC, graemerocher requested changes

2024-10-31 08:51 UTC, graemerocher commented on multitenancy/src/main/java/io/micronaut/multitenancy/filter/TenantResolverExistsCondition.java
> +                || context.getBeanContext().containsBean(TenantResolver.class);
reuse the `beanContext` variable in this second condition

2024-10-31 08:51 UTC, graemerocher commented on multitenancy/src/main/java/io/micronaut/multitenancy/SerializableTenant.java
> +public interface SerializableTenant extends Tenant<Serializable>  {
do we need this given that `TenantResolver` turns `Serializable`? Perhaps `Tenant` should  be `Tenant<T extends Serializable>` and then you can simply inject `Tenant<?>` or `Tenant<Whatever>` if you know the type

2024-10-31 08:51 UTC, graemerocher commented on multitenancy/src/main/java/io/micronaut/multitenancy/filter/TenantTypedRequestArgumentBinder.java
> +final class TenantTypedRequestArgumentBinder implements TypedRequestArgumentBinder<SerializableTenant> {
this should be `TypedRequestArgumentBinder<Tenant<T>>` and then in the `bind` method you should check from the `context` that the resolved tenant matches the generic type

2024-10-31 10:35 UTC, sdelamo commented on multitenancy/src/main/java/io/micronaut/multitenancy/filter/TenantResolverExistsCondition.java
> +                || context.getBeanContext().containsBean(TenantResolver.class);
resolved via https://github.com/micronaut-projects/micronaut-multitenancy/pull/343/commits/58f0bfe2f356df05a929f997e6ec36e04092ca18

2024-10-31 10:36 UTC, sdelamo commented on multitenancy/src/main/java/io/micronaut/multitenancy/SerializableTenant.java
> +public interface SerializableTenant extends Tenant<Serializable>  {
I removed it in https://github.com/micronaut-projects/micronaut-multitenancy/pull/343/commits/1483ca6461d373ffefd9e048405ed187d8ae7b3b

2024-10-31 10:49 UTC, sdelamo commented on multitenancy/src/main/java/io/micronaut/multitenancy/filter/TenantTypedRequestArgumentBinder.java
> +final class TenantTypedRequestArgumentBinder implements TypedRequestArgumentBinder<SerializableTenant> {
I tried with: 

```java
import io.micronaut.core.annotation.Internal;
import io.micronaut.core.convert.ArgumentConversionContext;
import io.micronaut.core.reflect.GenericTypeUtils;
import io.micronaut.core.type.Argument;
import io.micronaut.core.util.ArrayUtils;
import io.micronaut.http.HttpRequest;
import io.micronaut.http.bind.binders.TypedRequestArgumentBinder;
import io.micronaut.multitenancy.Tenant;
import jakarta.inject.Singleton;

import java.io.Serializable;
import java.util.Optional;

/**
 * {@link TypedRequestArgumentBinder} for {@link Tenant}.
 * @author Sergio del Amo
 * @since 5.5.0
 */
@Internal
@Singleton
final class TenantTypedRequestArgumentBinder<T extends Serializable> implements TypedRequestArgumentBinder<Tenant<T>> {

    @SuppressWarnings("unchecked")
    private final Class<T> requestType = initTypeArgument(0);

    @Override
    public Argument<Tenant<T>> argumentType() {
        return Argument.of((Class<Tenant<T>>) (Class<?>) Tenant.class, requestType);
    }

    @Override
    public BindingResult<Tenant<T>> bind(ArgumentConversionContext<Tenant<T>> context, HttpRequest<?> source) {
        if (!source.getAttributes().contains(TenantResolverFilter.ATTRIBUTE_TENANT)) {
            return BindingResult.UNSATISFIED;
        }
        Optional<T> idType = source.getAttribute(TenantResolverFilter.ATTRIBUTE_TENANT, requestType);
        if (idType.isEmpty()) {
            return BindingResult.EMPTY;
        }
        T serializable = idType.get();
        Tenant<T> tenant = () -> serializable;
        return () -> Optional.of(tenant);
    }

    @SuppressWarnings("rawtypes")
    private Class initTypeArgument(int index) {
        final Class[] args = GenericTypeUtils.resolveSuperTypeGenericArguments(
                getClass(),
                TenantTypedRequestArgumentBinder.class
        );
        if (ArrayUtils.isNotEmpty(args) && args.length > index) {
            return args[index];
        } else {
            return Object.class;
        }
    }
}

```

But it does work to bind to `Tenant<Serializable>` in a controller. 

I set the PR to use a PR without generic `TypedRequestArgumentBinder<Tenant>` and that works.

2024-10-31 10:52 UTC, sdelamo commented on multitenancy/src/main/java/io/micronaut/multitenancy/filter/TenantTypedRequestArgumentBinder.java
> +final class TenantTypedRequestArgumentBinder implements TypedRequestArgumentBinder<SerializableTenant> {
Since the tenant resolved is always a `Serializable`. Would not be better to do : 

```java
@Internal
@Singleton
final class TenantTypedRequestArgumentBinder implements TypedRequestArgumentBinder<Tenant<Serializable>> {


    @Override
    public Argument<Tenant<Serializable>> argumentType() {
        return Argument.of((Class<Tenant<Serializable>>) (Class<?>) Tenant.class, Serializable.class);
    }

    @Override
    public BindingResult<Tenant<Serializable>> bind(ArgumentConversionContext<Tenant<Serializable>> context, HttpRequest<?> source) {
        if (!source.getAttributes().contains(TenantResolverFilter.ATTRIBUTE_TENANT)) {
            return BindingResult.UNSATISFIED;
        }
        Optional<Serializable> idType = source.getAttribute(TenantResolverFilter.ATTRIBUTE_TENANT, Serializable.class);
        if (idType.isEmpty()) {
            return BindingResult.EMPTY;
        }
        Serializable serializable = idType.get();
        Tenant<Serializable> tenant = () -> serializable;
        return () -> Optional.of(tenant);
    }
}
```

2024-10-31 11:09 UTC, yawkat commented on multitenancy/src/main/java/io/micronaut/multitenancy/filter/TenantResolverFilterConfigurationProperties.java
> +    public static final String  DEFAULT_REGEX_PATTERN = "^.*$";
```suggestion
    public static final String DEFAULT_REGEX_PATTERN = "^.*$";
```

Is checkstyle on? I think it would've caught this?

2024-10-31 11:10 UTC, yawkat commented on multitenancy/src/main/java/io/micronaut/multitenancy/filter/TenantTypedRequestArgumentBinder.java
> +        Optional<Serializable> serializableOptional = source.getAttribute(TenantResolverFilter.ATTRIBUTE_TENANT, Serializable.class);
Why Serializable?

2024-10-31 11:12 UTC, yawkat commented on multitenancy/src/main/java/io/micronaut/multitenancy/Tenant.java
> +public interface Tenant<T extends Serializable> {
Oh this is why.

I don't think this should be bound to Serializable, nobody uses java serialization.

2024-10-31 15:20 UTC, sdelamo commented on multitenancy/src/main/java/io/micronaut/multitenancy/filter/TenantTypedRequestArgumentBinder.java
> +        Optional<Serializable> serializableOptional = source.getAttribute(TenantResolverFilter.ATTRIBUTE_TENANT, Serializable.class);
Because [TenantResolver returns Serializable](https://github.com/micronaut-projects/micronaut-multitenancy/blob/5.5.x/multitenancy/src/main/java/io/micronaut/multitenancy/tenantresolver/TenantResolver.java#L57). Why? because we based it on the [Grails Tenant resolver design which returns Serializable](https://github.com/grails/grails-data-mapping/blob/9.0.x/grails-datastore-core/src/main/groovy/org/grails/datastore/mapping/multitenancy/TenantResolver.groovy).

2024-10-31 15:24 UTC, sdelamo commented on multitenancy/src/main/java/io/micronaut/multitenancy/Tenant.java
> +public interface Tenant<T extends Serializable> {
My original design return type for the id method was `String`. 
https://github.com/micronaut-projects/micronaut-multitenancy/pull/343/commits/ceabab71519e0144c1c6fa4998811c3bd91af2dd 

@graemerocher [thinks we should use a generic](https://github.com/micronaut-projects/micronaut-multitenancy/pull/343#discussion_r1822602256). And since tenant resolver returns serialisable, I set `T extends Serializable` 

Maybe it makes sense to get back to return a String. We control how we set the attribute in the filter and we can call `TenatnResolver::resolveIdentifier().toString`. thoughts @graemerocher @yawkat ?

2024-11-07 11:27 UTC, yawkat approved these changes

2024-11-07 13:12 UTC, dstepanov commented on multitenancy/src/main/java/io/micronaut/multitenancy/Tenant.java
> +public interface Tenant<T extends Serializable> {
Not even Hibernate requires a serializable ID

2024-11-07 13:14 UTC, dstepanov commented on multitenancy/src/main/java/io/micronaut/multitenancy/Tenant.java
> +public interface Tenant<T extends Serializable> {
Please don't use `Serializable`

2024-11-07 13:18 UTC, dstepanov requested changes

2024-11-07 13:18 UTC, dstepanov commented on multitenancy/src/main/java/io/micronaut/multitenancy/filter/TenantResolverFilter.java
> +final class TenantResolverFilter implements Ordered {
Why do you add HTTP stuff in multinenancy? This should be in some HTTP module

2024-11-07 13:18 UTC, dstepanov commented on src/main/docs/guide/multitenancy/tenantAsRequestAttribute.adoc
> +The module ships a filter which resolves the current tenant and sets it as a request attribute named `tenantIdentifier`.
It would be better to have some `TenantHttpAttributes.ID`

2024-11-07 14:25 UTC, graemerocher commented on multitenancy/src/main/java/io/micronaut/multitenancy/Tenant.java
> +public interface Tenant<T extends Serializable> {
the choice was because `TenatnResolver::resolveIdentifier` and changing that now would be a breaking change.

2024-11-12 10:41 UTC, sdelamo commented on src/main/docs/guide/multitenancy/tenantAsRequestAttribute.adoc
> +The module ships a filter which resolves the current tenant and sets it as a request attribute named `tenantIdentifier`.
Not sure I understand what you are requesting. There is an already a constant with value `tenantIdentifier` and name `TenantResolverFilter.ATTRIBUTE_TENANT`.

2024-11-12 10:43 UTC, sdelamo commented on multitenancy/src/main/java/io/micronaut/multitenancy/filter/TenantResolverFilter.java
> +final class TenantResolverFilter implements Ordered {
`micronaut-multitenancy` already depended on `http-server`. Most tenant resolvers were already http related. E.g. 
`CookieTenantResolver`, `HttpHeaderTenantResolver`, `SubdomainTenantResolver

2024-11-12 11:15 UTC, sdelamo commented on multitenancy/src/main/java/io/micronaut/multitenancy/Tenant.java
> +public interface Tenant<T extends Serializable> {
I added a `String resolveId` method to both `TenantResolver` and `HttpTenantResolver`. I have deprecated the `Serializable resolveIdentifier` methods. I use the `resolveId` in the filter now. Tenant is now simply : 

```java
public interface Tenant {
    String id();
}
```

2024-11-12 11:44 UTC, sdelamo commented on multitenancy/src/main/java/io/micronaut/multitenancy/filter/TenantResolverFilter.java
> +final class TenantResolverFilter implements Ordered {
`micronaut-http-server` is compileOnly and I have [added a test which verifies you can load the module without http](https://github.com/micronaut-projects/micronaut-multitenancy/pull/343/commits/642df363edb5c1529e658fe9e0944d4fe0ca0687)

2024-11-12 14:01 UTC, dstepanov approved these changes

2024-11-12 15:02 UTC, graemerocher approved these changes

2024-11-12 15:34 UTC, merged